version: "3"
services:
 elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.1"
  container_name: elasticsearch
  environment:
   - discovery.type=single-node
   - xpack.security.enabled=true
   - xpack.security.audit.enabled=true
   - xpack.security.authc.api_key.enabled=true
   - ELASTIC_PASSWORD=secret
  ports:
   - "9200:9200"
  networks:
   - eknetwork
 kibana:
  depends_on:
   - elasticsearch
  image: "docker.elastic.co/kibana/kibana:7.14.1"
  ports:
   - "5601:5601"
  environment:
   - ELASTICSEARCH_URL=http://localhost:9200
   - ELASTICSEARCH_USERNAME=elastic
   - ELASTICSEARCH_PASSWORD=secret
  networks:
   - eknetwork
networks:
 eknetwork:
  driver: bridge